### ISSUE TITLE
Добавить JS'ы для bootstrap и jQuery в проект

### ISSUE THREAD

**Issue by ademaro** [bogatyrevata/klasstrueda#31]

**Comment by bogatyrevata** [comment]
Скачать файлы js, jquery и заменить ссылки в базовом шаблоне: 
  <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">
  <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>

на файлы типа:

  <script src="{{ url_for('static', filename='js/wow.min.js') }}"></script>
